#docker build --rm -f Dockerfile.agent -t datakube//agent .

FROM golang:1.11-alpine as builder

ARG DEP_VERSION=0.4.1

RUN apk --update upgrade \
    && apk --no-cache --no-progress add git bash gcc musl-dev curl tar \
    && rm -rf /var/cache/apk/*

RUN mkdir -p /usr/local/bin \
    && curl -fsSL -o /usr/local/bin/dep https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 \
    && chmod +x /usr/local/bin/dep

WORKDIR /go/src/github.com/SantoDE/datakube/
COPY . /go/src/github.com/SantoDE/datakube/

RUN CGO_ENABLED=0 GOGC=off go build $FLAGS -ldflags "-X github.com/datakube/datakube/cmd/agent/version.Version=$VERSION -X github.com/datakube/datakube/cmd/agent/version.BuildDate=$DATE" -o dist/agent ./cmd/agent/

FROM alpine:3.6

RUN apk add --no-cache mysql-client && rm -rf /var/cache/apk/* && export PATH=/usr/bin/:~/bin:$PATH

COPY --from=builder /go/src/github.com/datakube/datakube/dist/agent /bin/datakube/-agent
ENTRYPOINT ["/bin/datakube/-agent"]

