// Code generated by protoc-gen-go. DO NOT EDIT.
// source: datakube.proto

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterRequest struct {
	Token                string    `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Targets              []*Target `protobuf:"bytes,2,rep,name=provider,proto3" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datakube_4a29893928a444d8, []int{0}
}
func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(dst, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RegisterRequest) GetTargets() []*Target {
	if m != nil {
		return m.Targets
	}
	return nil
}

type Job struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Target               *Target  `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_datakube_4a29893928a444d8, []int{1}
}
func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (dst *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(dst, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Job) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

type Target struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State                string       `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Credentials          *Credentials `protobuf:"bytes,3,opt,name=credentials,proto3" json:"credentials,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Target) Reset()         { *m = Target{} }
func (m *Target) String() string { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()    {}
func (*Target) Descriptor() ([]byte, []int) {
	return fileDescriptor_datakube_4a29893928a444d8, []int{2}
}
func (m *Target) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Target.Unmarshal(m, b)
}
func (m *Target) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Target.Marshal(b, m, deterministic)
}
func (dst *Target) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Target.Merge(dst, src)
}
func (m *Target) XXX_Size() int {
	return xxx_messageInfo_Target.Size(m)
}
func (m *Target) XXX_DiscardUnknown() {
	xxx_messageInfo_Target.DiscardUnknown(m)
}

var xxx_messageInfo_Target proto.InternalMessageInfo

func (m *Target) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Target) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Target) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

type Credentials struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Dbname               string   `protobuf:"bytes,4,opt,name=dbname,proto3" json:"dbname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_datakube_4a29893928a444d8, []int{3}
}
func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (dst *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(dst, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Credentials) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Credentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Credentials) GetDbname() string {
	if m != nil {
		return m.Dbname
	}
	return ""
}

type RegisterResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_datakube_4a29893928a444d8, []int{4}
}
func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(dst, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type SaveDumpFileRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Targetname           string   `protobuf:"bytes,2,opt,name=targetname,proto3" json:"targetname,omitempty"`
	Filename             string   `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveDumpFileRequest) Reset()         { *m = SaveDumpFileRequest{} }
func (m *SaveDumpFileRequest) String() string { return proto.CompactTextString(m) }
func (*SaveDumpFileRequest) ProtoMessage()    {}
func (*SaveDumpFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datakube_4a29893928a444d8, []int{5}
}
func (m *SaveDumpFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveDumpFileRequest.Unmarshal(m, b)
}
func (m *SaveDumpFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveDumpFileRequest.Marshal(b, m, deterministic)
}
func (dst *SaveDumpFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveDumpFileRequest.Merge(dst, src)
}
func (m *SaveDumpFileRequest) XXX_Size() int {
	return xxx_messageInfo_SaveDumpFileRequest.Size(m)
}
func (m *SaveDumpFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveDumpFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveDumpFileRequest proto.InternalMessageInfo

func (m *SaveDumpFileRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *SaveDumpFileRequest) GetTargetname() string {
	if m != nil {
		return m.Targetname
	}
	return ""
}

func (m *SaveDumpFileRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *SaveDumpFileRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SaveDumpFileResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveDumpFileResponse) Reset()         { *m = SaveDumpFileResponse{} }
func (m *SaveDumpFileResponse) String() string { return proto.CompactTextString(m) }
func (*SaveDumpFileResponse) ProtoMessage()    {}
func (*SaveDumpFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_datakube_4a29893928a444d8, []int{6}
}
func (m *SaveDumpFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveDumpFileResponse.Unmarshal(m, b)
}
func (m *SaveDumpFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveDumpFileResponse.Marshal(b, m, deterministic)
}
func (dst *SaveDumpFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveDumpFileResponse.Merge(dst, src)
}
func (m *SaveDumpFileResponse) XXX_Size() int {
	return xxx_messageInfo_SaveDumpFileResponse.Size(m)
}
func (m *SaveDumpFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveDumpFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveDumpFileResponse proto.InternalMessageInfo

func (m *SaveDumpFileResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ListJobsRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State                string   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Target               string   `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListJobsRequest) Reset()         { *m = ListJobsRequest{} }
func (m *ListJobsRequest) String() string { return proto.CompactTextString(m) }
func (*ListJobsRequest) ProtoMessage()    {}
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datakube_4a29893928a444d8, []int{7}
}
func (m *ListJobsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListJobsRequest.Unmarshal(m, b)
}
func (m *ListJobsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListJobsRequest.Marshal(b, m, deterministic)
}
func (dst *ListJobsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListJobsRequest.Merge(dst, src)
}
func (m *ListJobsRequest) XXX_Size() int {
	return xxx_messageInfo_ListJobsRequest.Size(m)
}
func (m *ListJobsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListJobsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListJobsRequest proto.InternalMessageInfo

func (m *ListJobsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListJobsRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *ListJobsRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

type ListJobsResponse struct {
	Jobs                 []*Job   `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListJobsResponse) Reset()         { *m = ListJobsResponse{} }
func (m *ListJobsResponse) String() string { return proto.CompactTextString(m) }
func (*ListJobsResponse) ProtoMessage()    {}
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_datakube_4a29893928a444d8, []int{8}
}
func (m *ListJobsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListJobsResponse.Unmarshal(m, b)
}
func (m *ListJobsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListJobsResponse.Marshal(b, m, deterministic)
}
func (dst *ListJobsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListJobsResponse.Merge(dst, src)
}
func (m *ListJobsResponse) XXX_Size() int {
	return xxx_messageInfo_ListJobsResponse.Size(m)
}
func (m *ListJobsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListJobsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListJobsResponse proto.InternalMessageInfo

func (m *ListJobsResponse) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "rpc.RegisterRequest")
	proto.RegisterType((*Job)(nil), "rpc.Job")
	proto.RegisterType((*Target)(nil), "rpc.Target")
	proto.RegisterType((*Credentials)(nil), "rpc.Credentials")
	proto.RegisterType((*RegisterResponse)(nil), "rpc.RegisterResponse")
	proto.RegisterType((*SaveDumpFileRequest)(nil), "rpc.SaveDumpFileRequest")
	proto.RegisterType((*SaveDumpFileResponse)(nil), "rpc.SaveDumpFileResponse")
	proto.RegisterType((*ListJobsRequest)(nil), "rpc.ListJobsRequest")
	proto.RegisterType((*ListJobsResponse)(nil), "rpc.ListJobsResponse")
}

func init() { proto.RegisterFile("datakube.proto", fileDescriptor_datakube_4a29893928a444d8) }

var fileDescriptor_datakube_4a29893928a444d8 = []byte{
	// 421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x25, 0x4d, 0xea, 0x3a, 0xe3, 0xaa, 0x8d, 0x16, 0x53, 0x99, 0x08, 0xa1, 0x68, 0x11, 0x52,
	0x0f, 0x28, 0xaa, 0xc2, 0x1d, 0x0e, 0x14, 0x0e, 0x11, 0x42, 0x62, 0xcb, 0x0f, 0xac, 0xed, 0x69,
	0x31, 0x4d, 0xbd, 0x66, 0x67, 0x0d, 0x07, 0xfe, 0x82, 0x2f, 0x46, 0x3b, 0x6b, 0x37, 0x26, 0x8a,
	0xa0, 0xb7, 0x99, 0xf7, 0x46, 0xef, 0xbd, 0xdd, 0x9d, 0x85, 0x93, 0x52, 0x3b, 0x7d, 0xdb, 0xe6,
	0xb8, 0x6c, 0xac, 0x71, 0x46, 0x8c, 0x6d, 0x53, 0xc8, 0x4f, 0x70, 0xaa, 0xf0, 0xa6, 0x22, 0x87,
	0x56, 0xe1, 0xf7, 0x16, 0xc9, 0x89, 0x14, 0x0e, 0x9d, 0xb9, 0xc5, 0x3a, 0x1b, 0x2d, 0x46, 0xe7,
	0x53, 0x15, 0x1a, 0xf1, 0x12, 0x8e, 0x9c, 0xb6, 0x37, 0xe8, 0x28, 0x3b, 0x58, 0x8c, 0xcf, 0x93,
	0x55, 0xb2, 0xb4, 0x4d, 0xb1, 0xfc, 0xc2, 0x98, 0xea, 0x39, 0xf9, 0x06, 0xc6, 0x6b, 0x93, 0x0b,
	0x01, 0x93, 0x5a, 0xdf, 0x61, 0x27, 0xc1, 0xb5, 0x78, 0x01, 0x51, 0x98, 0xca, 0x0e, 0x16, 0xa3,
	0x5d, 0x81, 0x8e, 0x92, 0xd7, 0x10, 0x05, 0x64, 0xaf, 0x44, 0x0a, 0x87, 0xe4, 0xb4, 0x43, 0x56,
	0x98, 0xaa, 0xd0, 0x88, 0x15, 0x24, 0x85, 0xc5, 0x12, 0x6b, 0x57, 0xe9, 0x0d, 0x65, 0x63, 0x56,
	0x9f, 0xb1, 0xfa, 0xbb, 0x2d, 0xae, 0x86, 0x43, 0xb2, 0x82, 0x64, 0xc0, 0x79, 0xb3, 0xaf, 0x86,
	0x5c, 0x6f, 0xe6, 0x6b, 0x8f, 0xb5, 0x84, 0xb6, 0xf3, 0xe2, 0x5a, 0xcc, 0x21, 0x6e, 0x34, 0xd1,
	0x4f, 0x63, 0x4b, 0xf6, 0x99, 0xaa, 0xfb, 0x5e, 0x9c, 0x41, 0x54, 0xe6, 0x1c, 0x79, 0xc2, 0x4c,
	0xd7, 0xc9, 0x57, 0x30, 0xdb, 0x5e, 0x31, 0x35, 0xa6, 0x26, 0x14, 0x19, 0x1c, 0x51, 0x5b, 0x14,
	0x48, 0xc4, 0x96, 0xb1, 0xea, 0x5b, 0xf9, 0x0b, 0x1e, 0x5f, 0xe9, 0x1f, 0x78, 0xd9, 0xde, 0x35,
	0x1f, 0xaa, 0x0d, 0xfe, 0xfb, 0x51, 0x9e, 0x03, 0x84, 0x7b, 0x63, 0xdb, 0x10, 0x74, 0x80, 0xf8,
	0xb8, 0xd7, 0xd5, 0x06, 0x99, 0xed, 0xe2, 0xf6, 0xbd, 0x3f, 0x9e, 0x5f, 0x08, 0x0e, 0x7b, 0xac,
	0xb8, 0x96, 0x17, 0x90, 0xfe, 0x6d, 0xfe, 0xdf, 0xb8, 0x57, 0x70, 0xfa, 0xb1, 0x22, 0xb7, 0x36,
	0x39, 0xf5, 0x51, 0x1f, 0xfe, 0x70, 0x67, 0xf7, 0x1b, 0x11, 0xc2, 0xf5, 0x4b, 0x70, 0x01, 0xb3,
	0xad, 0x68, 0x17, 0xe1, 0x19, 0x4c, 0xbe, 0x99, 0xdc, 0xfb, 0xfb, 0xe5, 0x8b, 0xf9, 0x75, 0xd7,
	0x26, 0x57, 0x8c, 0xae, 0x7e, 0x8f, 0x20, 0xbe, 0xec, 0xd6, 0x5b, 0xbc, 0x87, 0xe3, 0xe1, 0x29,
	0x44, 0xc6, 0xc3, 0x7b, 0x6e, 0x75, 0xfe, 0x74, 0x0f, 0x13, 0xfc, 0xe4, 0x23, 0xf1, 0x16, 0x4e,
	0x7c, 0x8a, 0xcf, 0x2d, 0xb6, 0x58, 0xfa, 0x2c, 0x22, 0xe5, 0xf1, 0x9d, 0xf3, 0xce, 0x9f, 0xec,
	0xa0, 0xbd, 0x40, 0x1e, 0xf1, 0x3f, 0x7b, 0xfd, 0x27, 0x00, 0x00, 0xff, 0xff, 0x2d, 0x9b, 0x29,
	0xc5, 0x79, 0x03, 0x00, 0x00,
}
