// Code generated by protoc-gen-go. DO NOT EDIT.
// source: datakube.proto

package datakube

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SaveDumpFileRequest struct {
	Targetname           string   `protobuf:"bytes,1,opt,name=targetname,proto3" json:"targetname,omitempty"`
	Filename             string   `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	JobId                int32    `protobuf:"varint,4,opt,name=jobId,proto3" json:"jobId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveDumpFileRequest) Reset()         { *m = SaveDumpFileRequest{} }
func (m *SaveDumpFileRequest) String() string { return proto.CompactTextString(m) }
func (*SaveDumpFileRequest) ProtoMessage()    {}
func (*SaveDumpFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datakube_bcf1cb208b6823e7, []int{0}
}
func (m *SaveDumpFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveDumpFileRequest.Unmarshal(m, b)
}
func (m *SaveDumpFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveDumpFileRequest.Marshal(b, m, deterministic)
}
func (dst *SaveDumpFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveDumpFileRequest.Merge(dst, src)
}
func (m *SaveDumpFileRequest) XXX_Size() int {
	return xxx_messageInfo_SaveDumpFileRequest.Size(m)
}
func (m *SaveDumpFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveDumpFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveDumpFileRequest proto.InternalMessageInfo

func (m *SaveDumpFileRequest) GetTargetname() string {
	if m != nil {
		return m.Targetname
	}
	return ""
}

func (m *SaveDumpFileRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *SaveDumpFileRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SaveDumpFileRequest) GetJobId() int32 {
	if m != nil {
		return m.JobId
	}
	return 0
}

type SaveDumpFileResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveDumpFileResponse) Reset()         { *m = SaveDumpFileResponse{} }
func (m *SaveDumpFileResponse) String() string { return proto.CompactTextString(m) }
func (*SaveDumpFileResponse) ProtoMessage()    {}
func (*SaveDumpFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_datakube_bcf1cb208b6823e7, []int{1}
}
func (m *SaveDumpFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveDumpFileResponse.Unmarshal(m, b)
}
func (m *SaveDumpFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveDumpFileResponse.Marshal(b, m, deterministic)
}
func (dst *SaveDumpFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveDumpFileResponse.Merge(dst, src)
}
func (m *SaveDumpFileResponse) XXX_Size() int {
	return xxx_messageInfo_SaveDumpFileResponse.Size(m)
}
func (m *SaveDumpFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveDumpFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveDumpFileResponse proto.InternalMessageInfo

func (m *SaveDumpFileResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ListJobsRequest struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListJobsRequest) Reset()         { *m = ListJobsRequest{} }
func (m *ListJobsRequest) String() string { return proto.CompactTextString(m) }
func (*ListJobsRequest) ProtoMessage()    {}
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datakube_bcf1cb208b6823e7, []int{2}
}
func (m *ListJobsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListJobsRequest.Unmarshal(m, b)
}
func (m *ListJobsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListJobsRequest.Marshal(b, m, deterministic)
}
func (dst *ListJobsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListJobsRequest.Merge(dst, src)
}
func (m *ListJobsRequest) XXX_Size() int {
	return xxx_messageInfo_ListJobsRequest.Size(m)
}
func (m *ListJobsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListJobsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListJobsRequest proto.InternalMessageInfo

func (m *ListJobsRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type UpdateJobRequest struct {
	Job                  *Job     `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateJobRequest) Reset()         { *m = UpdateJobRequest{} }
func (m *UpdateJobRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateJobRequest) ProtoMessage()    {}
func (*UpdateJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datakube_bcf1cb208b6823e7, []int{3}
}
func (m *UpdateJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateJobRequest.Unmarshal(m, b)
}
func (m *UpdateJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateJobRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateJobRequest.Merge(dst, src)
}
func (m *UpdateJobRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateJobRequest.Size(m)
}
func (m *UpdateJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateJobRequest proto.InternalMessageInfo

func (m *UpdateJobRequest) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type UpdateJobResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Job                  *Job     `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateJobResponse) Reset()         { *m = UpdateJobResponse{} }
func (m *UpdateJobResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateJobResponse) ProtoMessage()    {}
func (*UpdateJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_datakube_bcf1cb208b6823e7, []int{4}
}
func (m *UpdateJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateJobResponse.Unmarshal(m, b)
}
func (m *UpdateJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateJobResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateJobResponse.Merge(dst, src)
}
func (m *UpdateJobResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateJobResponse.Size(m)
}
func (m *UpdateJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateJobResponse proto.InternalMessageInfo

func (m *UpdateJobResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateJobResponse) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type Target struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string       `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Credentials          *Credentials `protobuf:"bytes,3,opt,name=credentials,proto3" json:"credentials,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Target) Reset()         { *m = Target{} }
func (m *Target) String() string { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()    {}
func (*Target) Descriptor() ([]byte, []int) {
	return fileDescriptor_datakube_bcf1cb208b6823e7, []int{5}
}
func (m *Target) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Target.Unmarshal(m, b)
}
func (m *Target) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Target.Marshal(b, m, deterministic)
}
func (dst *Target) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Target.Merge(dst, src)
}
func (m *Target) XXX_Size() int {
	return xxx_messageInfo_Target.Size(m)
}
func (m *Target) XXX_DiscardUnknown() {
	xxx_messageInfo_Target.DiscardUnknown(m)
}

var xxx_messageInfo_Target proto.InternalMessageInfo

func (m *Target) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Target) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Target) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

type Credentials struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 string   `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	User                 string   `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Database             string   `protobuf:"bytes,5,opt,name=database,proto3" json:"database,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_datakube_bcf1cb208b6823e7, []int{6}
}
func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (dst *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(dst, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Credentials) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *Credentials) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Credentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Credentials) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type Job struct {
	Target               *Target  `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	State                string   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Id                   int32    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_datakube_bcf1cb208b6823e7, []int{7}
}
func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (dst *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(dst, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *Job) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Job) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListJobsResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Jobs                 []*Job   `protobuf:"bytes,2,rep,name=jobs,proto3" json:"jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListJobsResponse) Reset()         { *m = ListJobsResponse{} }
func (m *ListJobsResponse) String() string { return proto.CompactTextString(m) }
func (*ListJobsResponse) ProtoMessage()    {}
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_datakube_bcf1cb208b6823e7, []int{8}
}
func (m *ListJobsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListJobsResponse.Unmarshal(m, b)
}
func (m *ListJobsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListJobsResponse.Marshal(b, m, deterministic)
}
func (dst *ListJobsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListJobsResponse.Merge(dst, src)
}
func (m *ListJobsResponse) XXX_Size() int {
	return xxx_messageInfo_ListJobsResponse.Size(m)
}
func (m *ListJobsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListJobsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListJobsResponse proto.InternalMessageInfo

func (m *ListJobsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ListJobsResponse) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func init() {
	proto.RegisterType((*SaveDumpFileRequest)(nil), "datakube.SaveDumpFileRequest")
	proto.RegisterType((*SaveDumpFileResponse)(nil), "datakube.SaveDumpFileResponse")
	proto.RegisterType((*ListJobsRequest)(nil), "datakube.ListJobsRequest")
	proto.RegisterType((*UpdateJobRequest)(nil), "datakube.UpdateJobRequest")
	proto.RegisterType((*UpdateJobResponse)(nil), "datakube.UpdateJobResponse")
	proto.RegisterType((*Target)(nil), "datakube.Target")
	proto.RegisterType((*Credentials)(nil), "datakube.Credentials")
	proto.RegisterType((*Job)(nil), "datakube.Job")
	proto.RegisterType((*ListJobsResponse)(nil), "datakube.ListJobsResponse")
}

func init() { proto.RegisterFile("datakube.proto", fileDescriptor_datakube_bcf1cb208b6823e7) }

var fileDescriptor_datakube_bcf1cb208b6823e7 = []byte{
	// 463 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x25, 0x69, 0x1b, 0x92, 0x09, 0x2c, 0xc5, 0x2c, 0x28, 0x04, 0xb1, 0x04, 0x9f, 0xc2, 0x65,
	0x85, 0xba, 0x07, 0x3e, 0x60, 0x51, 0x25, 0x2a, 0x04, 0x92, 0xa1, 0x1f, 0x60, 0x37, 0x06, 0x52,
	0xba, 0x75, 0xc8, 0x38, 0x20, 0xc4, 0x89, 0x1f, 0xe6, 0x1b, 0x90, 0x9d, 0x38, 0x09, 0x4b, 0x57,
	0xbd, 0xcd, 0xf3, 0x9b, 0xcc, 0xbc, 0xbc, 0x99, 0x81, 0x93, 0x82, 0x6b, 0xfe, 0xb5, 0x11, 0xf2,
	0xbc, 0xaa, 0x95, 0x56, 0x24, 0x74, 0x98, 0xfe, 0x82, 0x07, 0x1f, 0xf8, 0x77, 0xf9, 0xba, 0xb9,
	0xaa, 0x96, 0xe5, 0x4e, 0x32, 0xf9, 0xad, 0x91, 0xa8, 0xc9, 0x19, 0x80, 0xe6, 0xf5, 0x67, 0xa9,
	0xf7, 0xfc, 0x4a, 0x26, 0x5e, 0xe6, 0xe5, 0x11, 0x1b, 0xbd, 0x90, 0x14, 0xc2, 0x4f, 0xe5, 0x4e,
	0x5a, 0xd6, 0xb7, 0x6c, 0x8f, 0x09, 0x81, 0xa9, 0x29, 0x9f, 0x4c, 0x32, 0x2f, 0xbf, 0xc3, 0x6c,
	0x4c, 0x4e, 0x61, 0xb6, 0x55, 0xe2, 0x4d, 0x91, 0x4c, 0x33, 0x2f, 0x9f, 0xb1, 0x16, 0xd0, 0x97,
	0x70, 0xfa, 0x6f, 0x73, 0xac, 0xd4, 0x1e, 0x25, 0x49, 0xe0, 0x36, 0x36, 0x9b, 0x8d, 0x44, 0xb4,
	0xad, 0x43, 0xe6, 0x20, 0x7d, 0x01, 0xf7, 0xde, 0x96, 0xa8, 0x57, 0x4a, 0xa0, 0x93, 0xfa, 0x08,
	0x02, 0xd4, 0x5c, 0x37, 0xd8, 0xc9, 0xec, 0x10, 0xbd, 0x80, 0xf9, 0xba, 0x2a, 0xb8, 0x96, 0x2b,
	0x25, 0x5c, 0xee, 0x33, 0x98, 0x6c, 0x95, 0xb0, 0x89, 0xf1, 0xe2, 0xee, 0x79, 0xef, 0x8a, 0x49,
	0x31, 0x0c, 0x7d, 0x07, 0xf7, 0x47, 0x1f, 0x1d, 0x93, 0xe3, 0xea, 0xf9, 0x37, 0xd6, 0x2b, 0x21,
	0xf8, 0x68, 0x5d, 0x33, 0xae, 0x8c, 0xbc, 0x9c, 0x3a, 0xa7, 0xf4, 0xcf, 0xca, 0x39, 0x68, 0x63,
	0xf2, 0x0a, 0xe2, 0x4d, 0x2d, 0x0b, 0xb9, 0xd7, 0x25, 0xdf, 0xa1, 0x35, 0x31, 0x5e, 0x3c, 0x1c,
	0x4a, 0x5f, 0x0e, 0x24, 0x1b, 0x67, 0xd2, 0xdf, 0x1e, 0xc4, 0x23, 0xd2, 0x14, 0xff, 0xa2, 0x50,
	0xbb, 0x86, 0x26, 0x36, 0x6f, 0x95, 0xaa, 0xb5, 0x6b, 0x68, 0x62, 0xf3, 0xd6, 0xa0, 0xac, 0x6d,
	0xa7, 0x88, 0xd9, 0xd8, 0x8c, 0xb7, 0xe2, 0x88, 0x3f, 0x54, 0xdd, 0x4e, 0x2c, 0x62, 0x3d, 0x36,
	0x9c, 0x11, 0x23, 0x38, 0xca, 0x64, 0xd6, 0x72, 0x0e, 0xd3, 0x35, 0x4c, 0x56, 0x4a, 0x90, 0x1c,
	0x82, 0x76, 0x57, 0x3a, 0xa7, 0xe7, 0x83, 0xfc, 0xd6, 0x0d, 0xd6, 0xf1, 0x66, 0x2f, 0xcc, 0xb8,
	0x9c, 0x05, 0x2d, 0x20, 0x27, 0xe0, 0x97, 0x85, 0x15, 0x34, 0x63, 0x7e, 0x59, 0xd0, 0xf7, 0x30,
	0x1f, 0xa6, 0x7e, 0x74, 0x28, 0xcf, 0x61, 0xba, 0x55, 0x02, 0x13, 0x3f, 0x9b, 0xfc, 0x3f, 0x15,
	0x4b, 0x2d, 0xfe, 0x78, 0xd0, 0x9f, 0x00, 0x59, 0x03, 0x19, 0x6f, 0xe1, 0x52, 0xd5, 0xe6, 0x1f,
	0x9e, 0x0e, 0xdf, 0x1d, 0x38, 0x90, 0xf4, 0xec, 0x26, 0xba, 0x95, 0x47, 0x6f, 0x91, 0x4b, 0x08,
	0x9d, 0x68, 0xf2, 0x78, 0xc8, 0xbe, 0xb6, 0xbe, 0x69, 0x7a, 0x88, 0xea, 0x8b, 0x2c, 0x21, 0xea,
	0xf7, 0x91, 0x8c, 0x52, 0xaf, 0x6f, 0x76, 0xfa, 0xe4, 0x20, 0xe7, 0xea, 0x88, 0xc0, 0xde, 0xfd,
	0xc5, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x6b, 0x22, 0x43, 0x09, 0x04, 0x00, 0x00,
}
