#!/bin/bash
set -e

rm -f dist/worker

FLAGS=""
if [ -n "$VERBOSE" ]; then
    FLAGS="${FLAGS} -v"
fi

if [ -z "$VERSION" ]; then
    VERSION=$(git rev-parse HEAD)
fi

if [ -z "$DATE" ]; then
    DATE=$(date -u '+%Y-%m-%d_%I:%M:%S%p')
fi

# Build binaries
CGO_ENABLED=0 GOGC=off go build $FLAGS -ldflags "-s -w -X github.com/SantoDE/datahamster/worker/version.Version=$VERSION -X github.com/SantoDE/datahamster/worker/version.BuildDate=$DATE" -a -installsuffix nocgo -o dist/datahamster-worker .