#!/bin/bash
set -e

rm -f dist/worker

FLAGS=""
if [ -n "$VERBOSE" ]; then
    FLAGS="${FLAGS} -v"
fi

if [ -z "$VERSION" ]; then
    VERSION=$(git rev-parse HEAD)
fi

if [ -z "$DATE" ]; then
    DATE=$(date -u '+%Y-%m-%d_%I:%M:%S%p')
fi

# Build binaries
CGO_ENABLED=0 GOGC=off go build $FLAGS -ldflags "-X github.com/datakube/datakube/cmd/dumper/version.Version=$VERSION -X github.com/datakube/datakube/cmd/dumper/version.BuildDate=$DATE" -o dist/worker ./cmd/dumper/