#!/bin/bash
set -e

if [ -z "$VERSION" ]; then
    VERSION=$(git rev-parse HEAD)
fi

if [ -z "$DATE" ]; then
    DATE=$(date -u '+%Y-%m-%d_%I:%M:%S%p')
fi

# Get rid of existing binaries
rm -rf dist/
mkdir dist
mkdir dist/agent
mkdir dist/server

# Build 386 amd64 binaries
OS_PLATFORM_ARG=(linux darwin windows)
OS_ARCH_ARG=(386 amd64)
for OS in ${OS_PLATFORM_ARG[@]}; do
  for ARCH in ${OS_ARCH_ARG[@]}; do
    echo "Building binaries for $OS/$ARCH..."
    GOARCH=$ARCH GOOS=$OS CGO_ENABLED=0 go build -ldflags "-s -w -X github.com/datakube/datakube/cmd/agent/version.Version=$VERSION -X github.com/datakube/datakube/cmd/agent/version.BuildDate=$DATE" -o "dist/agent/datakube-agent_$OS-$ARCH" ./cmd/agent
    GOARCH=$ARCH GOOS=$OS CGO_ENABLED=0 go build -ldflags "-s -w -X github.com/datakube/datakube/cmd/server/version.Version=$VERSION -X github.com/datakube/datakube/cmd/server/version.BuildDate=$DATE" -o "dist/server/datakube-server_$OS-$ARCH" ./cmd/server
  done
done