#!/usr/bin/env bash

source "$(dirname "$BASH_SOURCE")/.validate"

badFiles=()

for file in ${files} ;
do
	if [ "$(gofmt -s -l "$file")" ]; then
		badFiles+=( "$file" )
	fi
done;

if [ ${#badFiles[@]} -eq 0 ]; then
	echo 'Congratulations!  All Go source files are properly formatted.'
else
	{
		echo "These files are not properly gofmt'd:"
		for f in "${badFiles[@]}"; do
			echo " - $f"
		done
		echo
		echo 'Please reformat the above files using "gofmt -s -w" and commit the result.'
		echo
	} >&2
	false
fi