/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	backuptargetv1 "github.com/datakube/datakube/pkg/apis/backuptarget/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBackupTargets implements BackupTargetInterface
type FakeBackupTargets struct {
	Fake *FakeDatakubeV1
	ns   string
}

var backuptargetsResource = schema.GroupVersionResource{Group: "datakube.io", Version: "v1", Resource: "backuptargets"}

var backuptargetsKind = schema.GroupVersionKind{Group: "datakube.io", Version: "v1", Kind: "BackupTarget"}

// Get takes name of the backupTarget, and returns the corresponding backupTarget object, and an error if there is any.
func (c *FakeBackupTargets) Get(name string, options v1.GetOptions) (result *backuptargetv1.BackupTarget, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(backuptargetsResource, c.ns, name), &backuptargetv1.BackupTarget{})

	if obj == nil {
		return nil, err
	}
	return obj.(*backuptargetv1.BackupTarget), err
}

// List takes label and field selectors, and returns the list of BackupTargets that match those selectors.
func (c *FakeBackupTargets) List(opts v1.ListOptions) (result *backuptargetv1.BackupTargetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(backuptargetsResource, backuptargetsKind, c.ns, opts), &backuptargetv1.BackupTargetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &backuptargetv1.BackupTargetList{ListMeta: obj.(*backuptargetv1.BackupTargetList).ListMeta}
	for _, item := range obj.(*backuptargetv1.BackupTargetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested backupTargets.
func (c *FakeBackupTargets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(backuptargetsResource, c.ns, opts))

}

// Create takes the representation of a backupTarget and creates it.  Returns the server's representation of the backupTarget, and an error, if there is any.
func (c *FakeBackupTargets) Create(backupTarget *backuptargetv1.BackupTarget) (result *backuptargetv1.BackupTarget, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(backuptargetsResource, c.ns, backupTarget), &backuptargetv1.BackupTarget{})

	if obj == nil {
		return nil, err
	}
	return obj.(*backuptargetv1.BackupTarget), err
}

// Update takes the representation of a backupTarget and updates it. Returns the server's representation of the backupTarget, and an error, if there is any.
func (c *FakeBackupTargets) Update(backupTarget *backuptargetv1.BackupTarget) (result *backuptargetv1.BackupTarget, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(backuptargetsResource, c.ns, backupTarget), &backuptargetv1.BackupTarget{})

	if obj == nil {
		return nil, err
	}
	return obj.(*backuptargetv1.BackupTarget), err
}

// Delete takes name of the backupTarget and deletes it. Returns an error if one occurs.
func (c *FakeBackupTargets) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(backuptargetsResource, c.ns, name), &backuptargetv1.BackupTarget{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBackupTargets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(backuptargetsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &backuptargetv1.BackupTargetList{})
	return err
}

// Patch applies the patch and returns the patched backupTarget.
func (c *FakeBackupTargets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *backuptargetv1.BackupTarget, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(backuptargetsResource, c.ns, name, data, subresources...), &backuptargetv1.BackupTarget{})

	if obj == nil {
		return nil, err
	}
	return obj.(*backuptargetv1.BackupTarget), err
}
