FROM mariadb:latest
MAINTAINER Manuel Laufenberg <hello@manuel-laufenberg.de>

ADD integration/fixtures/dump_test_table.sql /docker-entrypoint-initdb.d/dump_test_table.sql

ENTRYPOINT ["docker-entrypoint.sh"]

EXPOSE 3306
CMD ["mysqld"]